name: Lint Workflows

on:
  push:
    paths:
      - .github/workflows/*.yml
      - .github/workflows/*.yaml
  pull_request:
    paths:
      - .github/workflows/*.yml
      - .github/workflows/*.yaml
  workflow_dispatch:

jobs:
  actionlint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Lint GitHub Actions workflows
        uses: raven-actions/actionlint@v2
        with:
          fail_on_error: true
